WEBSITES = {
    "SCRAPE_GAMERANT_WEBSITE": True,
    "SCRAP_HULU_WEBSITE":True,
    "MAX_HBO_WEBSITE":True,
    "NETFLIX_WEBSITE": True,
    "NINTENDO_WEBSITE":True,
    "PRIME_WEBSITE":True,
    "XBOX_GAMES_WEBSITE": True
}
