XBOX_GAMES_WEBSITE_URL = 'https://www.xbox.com/en-us/games/all-games?cat=upcoming#'
PRIME_WEBSITE_URL = 'https://www.tvguide.com/news/new-on-amazon-prime-video/'
NETFLIX_WEBSITE_URL = 'https://www.tvguide.com/news/new-on-netflix/'
NEW_ON_MAX_HBO_WEBSITE_URL = 'https://www.tvguide.com/news/new-on-max-hbo/'
NEW_ON_HULU_WEBSITE_URL = 'https://www.tvguide.com/news/new-on-hulu/'
NINTENDO_WEBSITE_URL = 'https://www.nintendo.com/us/store/games/coming-soon/#sort=df&p=0'
GAMERANT_WEBSITE_URL = 'https://gamerant.com/ps5-game-release-dates/'
SEPHORA_WEBSITE_URL = "https://www.sephora.com/beauty/beauty-offers"
BUBBLE_EVENT_URL = "https://evenigo.com/version-test/api/1.1/obj/event"
BUBBLE_CALENDAR_URL = "https://evenigo.com/version-test/api/1.1/obj/calendar"
BUBBLE_IMAGE_URL = "https://evenigo.com/version-test/api/1.1/obj/Event-image"
